import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Input, Checkbox, Form } from "antd";
import myStyles from '../styles/MyComponent.module.css'
import { useState } from 'react'

const Home: NextPage = () => {
  const [loadings, setLoadings] = useState([]);
  const router = useRouter();

  const clickLogin = async () =>{
    await enterLoading(0);

    setTimeout(() =>{
      router.push('/home')
     }, 6000)
  }

  const enterLoading = async (index: number) => {

    setLoadings((prevLoadings) => {
      const newLoadings: any = [...prevLoadings];
      newLoadings[index] = true;
      return newLoadings;
    });

    setTimeout(() => {
      setLoadings((prevLoadings) => {
        const newLoadings: any = [...prevLoadings];
        newLoadings[index] = false;
        return newLoadings;
      });
    }, 6000);

  };

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main className={styles.main}>
        <div>
          <Image src="/logo.png" width="128px" height="64px" />
        </div>
        <Form
          name="basic"
          initialValues={{
            remember: true,
          }}
          onFinish={() => clickLogin()}
          // onFinishFailed={onFinishFailed}
          autoComplete="off"
        >
        <div style={{'marginTop': 24}}>
        
          <div>
          <Form.Item
            name="username"
            rules={[
              {
                required: true,
                message: 'โปรดกรอกอีเมล',
              },
            ]}
          >
            <Input className={myStyles.cspan} size='large' placeholder='อีเมล'></Input>
            </Form.Item>
          </div>
          <div>
          <Form.Item
            name="password"
            rules={[
              {
                required: true,
                message: 'โปรดกรอกรหัสผ่าน',
              },
            ]}
          >
            <Input className={myStyles.cspan} size='large' type={'password'} placeholder='รหัสผ่าน'></Input>
          </Form.Item>
          </div>
        </div>
        <div>
          <div>
            <Button
              htmlType="submit"
              className={`${myStyles.cspan} ${myStyles.cbutton}`}
              type="primary"
              onClick={() => null}
              loading={loadings[0]}
            >
              เข้าสู่ระบบ
            </Button>
          </div>
          <div>
            <Link href={'/register'}>
              <Button className={`${myStyles.cbutton}`} type="primary">สร้างบัญชีผู้ใช้</Button>
            </Link>
          </div>
        </div>
        </Form>
      </main>
    </div>
  )
}

export default Home
