import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Input, Checkbox, Form } from "antd";
import myStyles from '../styles/MyComponent.module.css'

const Register: NextPage = () => {
  const router = useRouter();
  const clickRegister = () =>{
    router.push('/')
  }
  return(
      <div className={styles.container}>
    {/* <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head> */}

    <main className={styles.main}>
    <Form
        name="basic"
        initialValues={{
          remember: true,
        }}
        onFinish={() => clickRegister()}
        // onFinishFailed={onFinishFailed}
        autoComplete="off"
      >
        <div style={{'marginBottom': 10, 'fontSize': 20, 'fontWeight': 'bold'}}>
          สร้างบัญชีผู้ใช้
        </div>
        <div style={{'marginBottom': 10}}>
          <div>
            <Form.Item
              name="email"
              rules={[
                {
                  required: true,
                  message: 'โปรดกรอกอีเมล',
                },
              ]}
            >
              <Input className={myStyles.cspan} size='large' placeholder='อีเมล'></Input>
            </Form.Item>
          </div>
          <div>
            <Form.Item
              name="password"
              rules={[
                {
                  required: true,
                  message: 'โปรดกรอกรหัสผ่าน',
                },
              ]}
            >
              <Input className={myStyles.cspan} size='large' type={'password'} placeholder='รหัสผ่าน'></Input>
            </Form.Item>
          </div>
          <div>
          <Form.Item
            name="confirmpassword"
            rules={[
              {
                required: true,
                message: 'โปรดกรอกรหัสผ่านอีกครั้ง',
              },
            ]}
          >
            <Input className={myStyles.cspan} size='large' type={'password'} placeholder='ยืนยันรหัสผ่าน'></Input>
          </Form.Item>
          </div>
          <div>
          <Form.Item
            name="accepttc"
            valuePropName="checked"
            rules={[
              {
                validator: (_, value) =>
                  value ? Promise.resolve() : Promise.reject(new Error('โปรดยอมรับเงื่อนไข')),
              },
            ]}
          >
          <Checkbox>ฉันยอมรับเงื่อนไขและข้อตกลงการใช้งาน</Checkbox>
          </Form.Item>
          </div>
        </div>
        <div>
          <div>
            <Button htmlType="submit" className={`${myStyles.cspan} ${myStyles.cbutton}`} type="primary">ยืนยัน</Button>
          </div>
        </div>
      </Form>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
  )
}

export default Register